name: CI

on: 
    pull_request: 
    push: 
        branches: 
            - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to AWS
    needs: test

  # Deploy only for a push to main, never for pull requests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
  
    environment:
      name: production
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Inspect GitHub OIDC claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: sts.amazonaws.com

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: github-static-site-deployment
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy App to AWS S3
        run: |
          aws s3 sync ./src "s3://${{ vars.S3_BUCKET_NAME }}" \ 
            --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
            